spring:
  config:
    import: "optional:configserver:"
  data:
    mongodb:
      URI: "mongodb://localhost:27017/sanguinedb"

server:
  port: "8080"

spring.main.web-application-type:
  reactive

spring.main.allow-bean-definition-overriding:
  true
